FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update -qq && apt-get install -y -qq build-essential libssl-dev > /dev/null 2>&1

WORKDIR /build
COPY src/ /build/

RUN make -f Makefile.debug clean && make -f Makefile.debug

# Create handout
RUN mkdir -p /handout && \
    cp /build/reverseme /handout/ && \
    cp /build/challenge /handout/

RUN tar -czf /handout.tar.gz /handout

CMD ["/build/reverseme"]
